<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\Auth\SocialLoginController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Home Route (Welcome Page)
Route::get('/', function () {
    return view('welcome');
});

// Dashboard Route (Only accessible for authenticated users)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Authenticated routes group
Route::middleware('auth')->group(function () {
    // Profile Routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');

    // Resource Routes for Departments and Students
    Route::resource('departments', DepartmentController::class);
    Route::get('departments/export', [DepartmentController::class, 'export']);
    Route::post('departments/import', [DepartmentController::class, 'import']);
    
    Route::resource('students', StudentController::class);

    // User export/import Routes
   
    // Logout Route
    Route::post('/logout', function () {
        Auth::logout();
        session()->invalidate();
        session()->regenerateToken();
        return redirect('/login');
    })->name('logout');
});

// Social Login Routes
Route::group(['prefix' => 'login'], function () {
    Route::get('google/redirect', [SocialLoginController::class, 'redirectToGoogle'])->name('login.google.redirect');
    Route::get('google/callback', [SocialLoginController::class, 'handleGoogleCallback']);
});




// Include Auth Routes (usually generated by `php artisan auth` or `breeze`/`jetstream`)
require __DIR__.'/auth.php';
